#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

## Feature Representation in LLMs

1. **Embeddings as Vectors (1D Arrays)**  
   - Each token (word/subword) is mapped to a fixed-length embedding vector.  
   - Internally stored as a 1D array of floats, e.g. `[0.12, -0.38, …, 1.07]`.  

2. **Batch Inputs as Matrices (2D Arrays)**  
   - A sequence of \(N\) tokens ⇒ an \(N \times D\) matrix, where \(D\) is embedding size.  
   - Enables parallel processing: each row is one token’s feature vector.  

3. **Model Parameters as Matrices/Tensors**  
   - Attention weights, feed-forward layers, projection layers: multi-dimensional arrays.  
   - e.g. query/key/value matrices of shape \(D \times D\); weight tensors in transformers are 3D+ when including multi-head dimensions.  

4. **Why Both?**  
   - **Arrays** (vectors) succinctly represent single token features.  
   - **Matrices/Tensors** enable batch operations and efficient linear algebra on GPUs/TPUs.

In [2]:
!pip install numpy

`arr1.shape` returns a **tuple** indicating the **dimensions** of the NumPy array `arr1`. For a 1D array, it's `(number_of_elements,)`. For a 2D array (like a matrix), it's `(number_of_rows, number_of_columns)`, and so on. It tells you the "size" of each axis.

In [34]:
import numpy as np

## create array using numpy
##create a 1D array
# arr1=np.array( [1,2,3,4,5] ) # 1D

arr1=np.array( [ [1,2,3,4,5] , [4,5,6,7,8] ] ) # 2D
# print(arr1)
# print(type(arr1))
print(arr1.shape)

(2, 5)


Reshape in NumPy changes the **shape** (number of rows and columns) of an array **without changing its data**. It gives you a different way to view the same elements.

In our example, `arr2.reshape(1,5)` transforms the 1D array `[1, 2, 3, 4, 5]` into a 2D array with **one row** and **five columns**: `[[1, 2, 3, 4, 5]]`.

In [37]:
## 1 d array
arr2=np.array( [1,2,3,4,5] ) # 1 D array

arr2.reshape(1,5)  ##1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [39]:
arr2=np.array([ [1,2,3,4,5] ]) # 2d
arr2.shape

(1, 5)

In [42]:
## 2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]]) # 2D arrya

print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [47]:
# np.arange(0,10,2)
demo = np.arange(0,10,2)

print(demo)
demo.shape

# becuase the .shape is 5 we are using 5 in the below
np.arange(0,10,2).reshape(5,1)


[0 2 4 6 8]


array([[0],
       [2],
       [4],
       [6],
       [8]])

`np.ones`
It creates a NumPy array with **3 rows** and **4 columns**, where **every element** in the array is the **number one** (as a float by default).

In [48]:
np.ones( (4,4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

`np.eye(3)` creates a **3x3 identity matrix** as a NumPy array. An identity matrix has ones on the main diagonal (top-left to bottom-right) and zeros everywhere else.

In [16]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
## Attributes of Numpy Array
arr = np.array( [ [1, 2, 3], [4, 5, 6]  ] )

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


In [19]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

## Element Wise Substraction
print("Substraction:", arr1-arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [80]:
## array slicing and Indexing

arr=np.array([
  [1,2,3,4],    #0
  [5,6,7,8],    #1  # 1:3
  [9,10,11,12]  #2  # 1:3
  ])
print("Array : \n", arr)



Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [81]:
# [ 5, 6, 7, 8 ]
#   0, 1, 2, 3

# [ 9, 10, 11, 12 ] 
#   0, 1,  2,  3
# print(arr[1:])
print(arr[1:,1:3]) # start:end-1

[[ 6  7]
 [10 11]]


In [82]:
#     0  1   2   3
#   [ 1, 2,  3,  4 ],    #0
#   [ 5, 6,  7,  8 ],    #1  # 1:3
#   [ 9, 10, 11, 12 ]    #2  # 1:3

# 1 is in which row?
# 0 0
# print(arr[2][0]) # [row] [column]
# print(arr[0:2])  # [row: row-1]
                   # [start: end-1]
print(arr[0:2,2:]) # [row: row-1] , [colum start: end-1]

#     0  1   2   3
#   [ 1, 2,  3,  4 ],    #0
#   [ 5, 6,  7,  8 ],    #1  # 1:3

[[3 4]
 [7 8]]


In [83]:
arr[1:,2:] # [start row: row-1] , [colum start: end-1]

array([[ 7,  8],
       [11, 12]])

In [84]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [86]:
arr[2:]=100 # [row: row-1] , [colum start: end-1]
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [100 100 100 100]]


In [26]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])